In [620]:
import xarray as xr
import numpy as np
from running_moments import run_norm

In [621]:
frames = np.random.randn(5,2,30)
time = np.random.randn(30) 
R = np.random.rand(5,2)
Z = np.random.rand(5,2)

ds = xr.Dataset(
    data_vars=dict(
        frames=(["y", "x", "time"], frames),
    ),
    coords=dict(
        R=(["y", "x"], R),
        Z=(["y", "x"], Z),
        time=time,
    ),
)
ds

<xarray.Dataset>
Dimensions:  (y: 5, x: 2, time: 30)
Coordinates:
    R        (y, x) float64 0.6416 0.3064 0.391 0.971 ... 0.3436 0.2816 0.2443
    Z        (y, x) float64 0.2648 0.7926 0.1235 0.9012 ... 0.2253 0.1992 0.3255
  * time     (time) float64 -0.9991 1.436 1.044 2.113 ... -0.3076 0.9574 -0.2961
Dimensions without coordinates: y, x
Data variables:
    frames   (y, x, time) float64 -0.4461 2.804 0.1059 ... -0.8563 -1.611 1.249

In [622]:
frames = np.zeros((5,2,30))
time = np.zeros(30) 
R = np.random.rand(5,2)
Z = np.random.rand(5,2)

ds = xr.Dataset(
    data_vars=dict(
        frames=(["y", "x", "time"], frames),
    ),
    coords=dict(
        R=(["y", "x"], R),
        Z=(["y", "x"], Z),
        time=time,
    ),
)
ds


<xarray.Dataset>
Dimensions:  (y: 5, x: 2, time: 30)
Coordinates:
    R        (y, x) float64 0.8503 0.3005 0.07318 ... 0.07943 0.3177 0.2873
    Z        (y, x) float64 0.9531 0.3057 0.8142 0.01063 ... 0.8361 0.412 0.7137
  * time     (time) float64 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0 0.0
Dimensions without coordinates: y, x
Data variables:
    frames   (y, x, time) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0

In [623]:
def increment_value(S: np.array, time: np.array):

    if S.ndim != 1 or time.ndim != 1:
        raise ValueError("array must be 1-D")

    return S + [1], time + [2]


In [624]:
a,b = increment_value(ds.isel(x=1,y=2)["frames"], ds["time"])

In [626]:
normalization = xr.apply_ufunc(
    increment_value,  # first the function
    ds.isel(x=1, y=2)["frames"],  # now arguments in the order expected by 'run_norm'
    ds['time'],
    input_core_dims=[["time"], ["time"]],  # list with one entry per arg
    output_core_dims=[["time"], ["time"]],
    exclude_dims=set(("time",)),  # dimensions allowed to change size. Must be set!
)
normalization

(<xarray.DataArray (time: 30)>
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 Coordinates:
     R        float64 0.5714
     Z        float64 0.6438
 Dimensions without coordinates: time,
 <xarray.DataArray (time: 30)>
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
 Coordinates:
     R        float64 0.5714
     Z        float64 0.6438
 Dimensions without coordinates: time)

In [630]:
normalization = xr.apply_ufunc(
    increment_value,  # first the function
    ds["frames"],  # now arguments in the order expected by 'run_norm'
    ds['time'],
    input_core_dims=[["time"], ["time"]],  # list with one entry per arg
    output_core_dims=[["time"], ["time"]],
    exclude_dims=set(("time",)),  # dimensions allowed to change size. Must be set!
    vectorize=True
)
type(normalization[0])


xarray.core.dataarray.DataArray

In [629]:
normalization

(<xarray.DataArray (y: 5, x: 2, time: 30)>
 array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1.

In [228]:
type(normalization[0])

numpy.ndarray

In [633]:
frames = np.random.randn(5,2,30)
time = np.random.randn(30) 
R = np.random.rand(5,2)
Z = np.random.rand(5,2)

ds = xr.Dataset(
    data_vars=dict(
        frames=(["y", "x", "time"], frames),
    ),
    coords=dict(
        R=(["y", "x"], R),
        Z=(["y", "x"], Z),
        time=time,
    ),
)

In [634]:
normalization = xr.apply_ufunc(
    run_norm,  # first the function
    ds['frames'],  # now arguments in the order expected by 'run_norm'
    5,
    ds['time'],
    input_core_dims=[["time"], [], ["time"]],  # list with one entry per arg
    output_core_dims=[["time"], ["time"]],
    exclude_dims=set(("time",)),  # dimensions allowed to change size. Must be 
    #exclude_dims=set(("time","frames"))  # dimensions allowed to change size. Must be set!
    vectorize=True
)

In [635]:
normalization[0]

<xarray.DataArray (y: 5, x: 2, time: 10)>
array([[[-1.21484197,  1.28056675,  0.70407988,  0.39550132,
         -0.41354787, -0.82937308, -1.41892171, -0.22519947,
          0.31796849, -0.28225492],
        [-2.08873138,  0.29511581,  1.3355533 , -0.63538684,
          0.29843644, -1.11196175,  1.32378612, -0.49533048,
          0.69166247,  0.89500383]],

       [[-0.76403345,  1.41311067,  0.51460671,  1.0418207 ,
         -0.06310496, -1.59184757,  0.45849343,  0.65617186,
         -0.60397957, -1.57530842],
        [-0.43355187,  0.22870709, -0.49487002,  0.89526317,
         -0.63892236, -1.36329862, -0.09917952,  1.5635619 ,
         -1.2930715 ,  1.01916097]],

       [[ 1.23651569, -0.87615833, -0.9254805 ,  0.93885989,
          1.13019749,  1.26429242, -1.49253803, -0.4728112 ,
         -1.31589443,  0.38148266],
        [ 0.19347288,  0.15261428,  1.89224993,  1.22918156,
         -1.77575806, -0.21708473,  0.37115552, -0.0779595 ,
         -1.2048205 ,  0.49738745]],

       [[ 0.02065963, -0.56193393, -0.06646866, -0.10448572,
          1.74634681, -0.3455907 ,  0.80884154, -0.192755  ,
         -1.07974299, -0.12516772],
        [ 2.37129846, -1.05347213,  0.66057858,  1.02372442,
         -0.57167889, -0.67008393, -0.95218925, -1.57264691,
          0.37437702,  1.12563767]],

       [[ 1.13818471,  1.57628191, -1.7079598 , -0.97069158,
          0.97093787,  0.653364  , -0.21103401, -0.54616034,
         -1.03152199, -1.38580827],
        [-1.8235486 ,  0.21935587,  1.05489471, -0.47442527,
          0.49940629,  1.16189476,  1.09836951, -0.50661539,
         -0.53475927, -1.09437616]]])
Coordinates:
    R        (y, x) float64 0.5338 0.01545 0.713 0.6122 ... 0.9741 0.6033 0.8365
    Z        (y, x) float64 0.2914 0.08386 0.9722 0.4331 ... 0.941 0.1579 0.5208
Dimensions without coordinates: y, x, time

In [636]:
normalization[1][0,0,:]

<xarray.DataArray (time: 10)>
array([ 0.21309129,  0.57924185, -1.68725724,  0.36244741, -1.35880899,
       -0.58641676, -0.04747645,  0.33602148,  0.22883488,  0.15854817])
Coordinates:
    R        float64 0.5338
    Z        float64 0.2914
Dimensions without coordinates: time

In [637]:
S, t = run_norm(ds.isel(x=0, y=0)["frames"].values, 5, ds["time"].values)

In [639]:
S

array([-1.21484197,  1.28056675,  0.70407988,  0.39550132, -0.41354787,
       -0.82937308, -1.41892171, -0.22519947,  0.31796849, -0.28225492])

In [640]:
t

array([ 0.21309129,  0.57924185, -1.68725724,  0.36244741, -1.35880899,
       -0.58641676, -0.04747645,  0.33602148,  0.22883488,  0.15854817])

In [616]:
new_ds = xr.Dataset(
    data_vars=dict(
        frames=(["y", "x", "time"], normalization[0].data),
    ),
    coords=dict(
        R=(["y", "x"], R),
        Z=(["y", "x"], Z),
        time=normalization[1].data[0,0,:],
    ),
)

In [618]:
new_ds["frames"]

<xarray.DataArray 'frames' (y: 5, x: 2, time: 10)>
array([[[-1.0269751 ,  1.5220647 , -0.44463863, -0.29281566,
          1.488522  ,  0.57475012,  0.49568921, -2.30038607,
          0.17939766,  0.03969971],
        [ 0.59329067,  1.37925461, -0.22726231,  1.35595485,
         -0.08985089,  0.66905461,  0.00609474, -0.50507802,
         -2.14495521, -0.69950545]],

       [[ 0.61519618, -1.17722458,  0.81804129, -0.40748184,
         -0.03115209, -1.86156658,  1.46016479, -0.46429501,
          0.66146313, -0.36734163],
        [ 1.06093765,  0.81839076, -2.2040352 ,  0.3408171 ,
          0.60244632,  0.97626705,  0.50711084, -0.63777956,
         -0.44228107, -0.38937619]],

       [[-0.93872296, -1.01377075,  0.00685414, -1.43803862,
          2.04631779,  0.22163545,  0.76555218, -1.29170857,
          0.370884  , -0.64084507],
        [-0.50503118, -0.82338361, -1.27349768,  0.28720558,
          1.21489799, -1.24005671,  0.10340684, -1.38107594,
          0.15158844,  0.46984749]],

       [[ 1.10210076,  0.46595389, -0.01911909, -0.74581948,
         -0.00756492, -0.20961071,  2.09950523,  0.45724279,
         -0.75839761, -1.47408823],
        [ 1.60159235,  0.5772201 ,  0.39626433, -0.75734575,
          0.82927784,  0.06678359, -0.66760701,  0.03828678,
          0.98875319, -2.78213718]],

       [[ 1.55152325, -0.08870015,  0.37308589,  0.05656837,
         -0.55831743,  0.29788787, -1.36136596,  1.53710375,
          1.38182937, -1.7961889 ],
        [ 0.07916562, -0.68410218, -0.90204598,  0.1291499 ,
          1.96046716, -1.48192979,  1.21279321, -0.44529951,
         -0.69507002,  0.22214991]]])
Coordinates:
    R        (y, x) float64 0.3522 0.1163 0.4104 0.2568 ... 0.58 0.6673 0.9731
    Z        (y, x) float64 0.4397 0.1293 0.0392 0.2069 ... 0.5785 0.2744 0.826
  * time     (time) float64 0.2049 0.7249 0.515 ... 0.03894 0.0726 0.00698
Dimensions without coordinates: y, x

In [642]:
s, t = run_norm(ds['frames'].values,  # now arguments in the order expected by 'run_norm'
    5,
    ds['time'].values)

ValueError: operands could not be broadcast together with shapes (0,2,30) (290,) 

In [643]:
normalization = xr.apply_ufunc(
    run_norm,  # first the function
    ds['frames'],  # now arguments in the order expected by 'run_norm'
    5,
    ds['time'],
    #input_core_dims=[["time"], ["time"], ["time"]],  # list with one entry per arg
    #output_core_dims=[["frames"], ["time"]],
    #exclude_dims=set(("time","frames"))  # dimensions allowed to change size. Must be set!
)

ValueError: operands could not be broadcast together with shapes (0,2,30) (290,) 